# .golangci.yml
version: "2"

linters:
  enable:
    - unused        # заменяет deadcode, structcheck, varcheck
    - gosimple      # дополнительные проверки простоты кода
    - govet         # проверки go vet
    - ineffassign   # неэффективные присваивания
    - staticcheck   # статический анализ
    - gosec         # проверки безопасности
    - goconst       # поиск магических строк
    - gocritic      # критические замечания
    - gofmt         # форматирование кода
    - goimports     # импорты

