# Рабочая конфигурация golangci-lint
linters:
  enable:
    - unused
    - gofmt
    - goimports
    - govet
  disable:
    - goanalysis_metalinter
    - buildir
    - gocyclo
    - gocognit
    - goconst
    - gocritic
    - gosec
    - gosimple
    - staticcheck

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - tests
  skip-files:
    - ".*_test.go"
