services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=postgres://langbot:password@db:5432/languagebot?sslmode=disable
      - DEBUG=true
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app  # Монтируем исходный код для разработки
    
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=langbot
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=languagebot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
      depends_on:
        - db

volumes:
  pgdata:
